---
format: html
---

## {{< fa seedling title="Sprouted seedling" >}} Create the scaffolding for your website 

::: callout-important
## Before getting started...

To follow along, you'll need:

-   [R](https://cloud.r-project.org/) & [RStudio](https://posit.co/download/rstudio-desktop/#download) installed 
-   [Quarto](https://quarto.org/docs/get-started/) installed -- **Quarto is now included with RStudio v2022.07.1+ i.e. no need for a separate download / install if you have the latest version of RStudio**
-   A [GitHub](https://github.com/) account
-   [Git](https://git-scm.com/) installed / configured
:::

This section reviews the **create remote (i.e. GitHub) repo *first* > clone repo to your local machine to add Quarto website scaffolding files *second*** workflow. If you need / want to instead use the *create a local repo with Quarto website scaffolding files first > create upstream remote (GitHub) repo second* workflow, check out [these instructions](https://ucsb-meds.github.io/creating-quarto-websites/#why-use-the-command-line-to-set-up-your-quarto-website).

### STEPS:

1. **Navigate to the GitHub profile or organization** where you want your website repository (repo) to live (this will likely be the [OHI-Science](https://github.com/OHI-Science) GitHub organization, but certainly doesn't have to be).

2. **Create and clone a GitHub repository** following the instructions, below. *Importantly, choose your repo name carefully*, as it'll become a part of the website's URL, once deployed (e.g. a repo named `my-awesome-repo` that lives in the `OHI-Science` organization will have a base URL, *https://OHI-Science/my-awesome-repo*).

::: {.callout-tip collapse=true}
## Step-by-step instructions for creating and cloning a GitHub repo:

**Create a GitHub (aka remote) repo:** 

1. Click on **Repositories tab** in the top menu bar
2. Click on the green **New repository** button in the upper right-hand corner
3. Give it a name, and optionally, a short description. Select the radio button for **Public** repo (it should be selected by default). ***DO NOT*** initialize the repo with a README or `.gitignore` (we can add these later). Click **Create repository**.
4. From your repo’s main page, click the green **Code** button and **copy the URL** to your clipboard

**Clone your repo:**

5. Open up RStudio
6. Click on the drop down menu next to the R project icon (top right corner)
7. Click **New Project...** > **Version Control** > **Git** > paste your repo's URL in the **Repository URL:** box and press **Tab** to auto fill the **Project directory name** field (it should automatically be named the same as your GitHub repo). **Browse to select where on your computer you'd like your repo to be saved.
8. Click **Create Project**
:::

3. **Add Quarto website scaffolding files** by running the following in your RStudio Terminal. Doing so will create the essential default website files (`_quarto.yml`, `.gitignore`, `index.qmd`, `about.qmd`, `styles.css`):

```{bash}
#| eval: false
#| echo: true
quarto create-project --type website
```


